apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: production
    release: production
    tier: worker
    track: stable
  name: production
  namespace: engine
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: production
      release: production
      tier: worker
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/application-secrets: ""
      creationTimestamp: null
      labels:
        app: production
        release: production
        tier: worker
        track: stable
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: production-secret
        image: IMAGE_URL
        imagePullPolicy: IfNotPresent
        name: engine
        resources:
          limits:
            cpu: "5"
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          exec:
            command:
              - ls
              - /opt/app/optimizations
          initialDelaySeconds: 10
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30