apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: staging
    release: staging
    tier: worker
    track: stable
  name: staging
  namespace: engine
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: staging
      release: staging
      tier: worker
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/application-secrets: ""
      creationTimestamp: null
      labels:
        app: staging
        release: staging
        tier: worker
        track: stable
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: staging-secret
        image: IMAGE_URL
        imagePullPolicy: IfNotPresent
        name: engine
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          exec:
            command:
              - ls
              - /opt/app/optimizations
          initialDelaySeconds: 10
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30