version: "3"

services:
  api:
    build:
      context: ../..
      dockerfile: packages/jobs-api/Dockerfile
    environment:
      - REDIS_URL=redis://@redis:6379/0
    ports:
      - 9000:5000
    # depends_on:
    #     - redis
  # redis:
  #     image: redis:4.0.5-alpine
  #     command: ['redis-server', '--appendonly', 'yes']
  #     hostname: redis
  #     networks:
  #         - redis-net
  #     volumes:
  #         - redis-data:/data
# volumes:
#   redis-data:
