export const preloadedSession = {
    deliveryPoints: [
        {
            name: 'ROKETAS ACCESSORIS',
            address: '41.443208,2.182843',
            id: '1',
            demand: 10,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27150,
                end: 29516,
            },
        },
        {
            name: 'ITRIDA VIATGES',
            address: '41.40375,2.169137',
            id: '2',
            demand: 39,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 25547,
                end: null,
            },
        },
        {
            name: 'JUGUETTOS',
            address: '41.374941,2.182894',
            id: '3',
            demand: 21,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 26716,
                end: 32194,
            },
        },
        {
            name: 'FOTOPRIX',
            address: '41.406678,2.163099',
            id: '4',
            demand: 29,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 26551,
                end: 28706,
            },
        },
        {
            name: 'VALLES SPORTS RUGBY',
            address: '41.370549,2.16087',
            id: '5',
            demand: 17,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28703,
                end: 30394,
            },
        },
        {
            name: 'LE PAIN QUOTIDIEN',
            address: '41.394503,2.150501',
            id: '6',
            demand: 43,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 25275,
                end: null,
            },
        },
        {
            name: "L'ESTEL",
            address: '41.425427,2.178259',
            id: '7',
            demand: 2,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 27759,
                end: null,
            },
        },
        {
            name: 'CREART TATTO LA BARCELONETA',
            address: '41.381453,2.18845',
            id: '8',
            demand: 47,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28786,
                end: null,
            },
        },
        {
            name: 'MONFRUIT',
            address: '41.409919,2.13625',
            id: '9',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27432,
                end: null,
            },
        },
        {
            name: 'OUTLET SPORTWEAR',
            address: '41.410665,2.172341',
            id: '10',
            demand: 23,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: null,
        },
        {
            name: 'GENEROS DE PUNTO PALANGUMA',
            address: '41.387421,2.176861',
            id: '11',
            demand: 30,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 26411,
                end: null,
            },
        },
        {
            name: 'RIA LOCUTORI',
            address: '41.429697,2.177149',
            id: '12',
            demand: 2,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28758,
                end: null,
            },
        },
        {
            name: 'LLIBRERIA HORITZONS',
            address: '41.38773,2.156533',
            id: '13',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 25629,
                end: 26299,
            },
        },
        {
            name: 'BAR RESTAURANT AQUI ESTOY',
            address: '41.382979,2.14279',
            id: '14',
            demand: 40,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 37481,
                end: 39716,
            },
        },
        {
            name: 'ASSOCIACIO CATALANA PER A LA PROMOCIO DE LES PERSONES SORDES',
            address: '41.406116,2.157435',
            id: '15',
            demand: 49,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 26690,
                end: null,
            },
        },
        {
            name: 'MOVING',
            address: '41.375249,2.173522',
            id: '16',
            demand: 4,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26706,
                end: null,
            },
        },
        {
            name: 'NOSTRUM',
            address: '41.399918,2.152136',
            id: '17',
            demand: 10,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 27020,
                end: null,
            },
        },
        {
            name: 'COSTURERA',
            address: '41.418816,2.20658',
            id: '18',
            demand: 3,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 27291,
                end: null,
            },
        },
        {
            name: 'CALCEDONIA',
            address: '41.393456,2.144908',
            id: '19',
            demand: 15,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 38058,
                end: 44027,
            },
        },
        {
            name: 'CONSULTA PODOLOGICA',
            address: '41.415401,2.196494',
            id: '20',
            demand: 10,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 36084,
                end: null,
            },
        },
        {
            name: "CLINICA DENTAL VALL D'HEBRON",
            address: '41.425005,2.139171',
            id: '21',
            demand: 6,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 25255,
                end: 32034,
            },
        },
        {
            name: 'ORMOLAB',
            address: '41.393599,2.176148',
            id: '22',
            demand: 44,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 27304,
                end: 29364,
            },
        },
        {
            name: 'NOSTRADAMUS',
            address: '41.381817,2.149766',
            id: '23',
            demand: 8,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 38925,
                end: null,
            },
        },
        {
            name: 'SOLIDCAM ESTUDIO',
            address: '41.396697,2.202211',
            id: '24',
            demand: 17,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 25556,
                end: 29335,
            },
        },
        {
            name: 'TABACS EXP. 97',
            address: '41.357296,2.143955',
            id: '25',
            demand: 12,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 28406,
                end: null,
            },
        },
        {
            name: 'HOTEL MODERNO',
            address: '41.381038,2.1727',
            id: '26',
            demand: 3,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 27117,
                end: null,
            },
        },
        {
            name: 'SYSTEMACTION',
            address: '41.400287,2.19585',
            id: '27',
            demand: 31,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 30118,
                end: null,
            },
        },
        {
            name: 'PHILAE',
            address: '41.428819,2.170868',
            id: '28',
            demand: 38,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 25747,
                end: 27636,
            },
        },
        {
            name: 'ANETT',
            address: '41.389495,2.176127',
            id: '29',
            demand: 43,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 39413,
                end: 39890,
            },
        },
        {
            name: 'BAR MIGUEL',
            address: '41.421505,2.198188',
            id: '30',
            demand: 25,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 37272,
                end: null,
            },
        },
        {
            name: 'BC SISTEMAS',
            address: '41.39731,2.182416',
            id: '31',
            demand: 2,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 37526,
                end: 44293,
            },
        },
        {
            name: 'FARMACIA CASTELL FORES',
            address: '41.388518,2.159757',
            id: '32',
            demand: 14,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 26397,
                end: null,
            },
        },
        {
            name: 'CLINICA DE PODOLOGIA ALMAR',
            address: '41.435017,2.170527',
            id: '33',
            demand: 35,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27075,
                end: 28425,
            },
        },
        {
            name: 'FRUITES I VERDURES',
            address: '41.418076,2.171522',
            id: '34',
            demand: 18,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 39340,
                end: 44678,
            },
        },
        {
            name: 'OJE BARCELONA ESCOLA ALMOGAVERS',
            address: '41.399102,2.178464',
            id: '35',
            demand: 14,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 27525,
                end: null,
            },
        },
        {
            name: 'BREADY & CASUAL FOOD',
            address: '41.408834,2.152703',
            id: '36',
            demand: 21,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 27774,
                end: null,
            },
        },
        {
            name: "O'RINCON GALEGO",
            address: '41.436436,2.184843',
            id: '37',
            demand: 9,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 38486,
                end: 40633,
            },
        },
        {
            name: 'BAR CERVESERIA PERNACHO',
            address: '41.353112,2.141982',
            id: '38',
            demand: 14,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 28158,
                end: null,
            },
        },
        {
            name: 'ZUCKERHAUS PASTELERIA',
            address: '41.376074,2.161765',
            id: '39',
            demand: 36,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: null,
        },
        {
            name: 'IBARFIL S.L.',
            address: '41.438435,2.178866',
            id: '40',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 29179,
                end: null,
            },
        },
        {
            name: 'ESCOLA DE DANSA STAGE',
            address: '41.413491,2.177841',
            id: '41',
            demand: 21,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 27171,
                end: null,
            },
        },
        {
            name: 'CASA DE LA ESPIRAL',
            address: '41.405509,2.161951',
            id: '42',
            demand: 41,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 27493,
                end: 29233,
            },
        },
        {
            name: 'M.I.L. 24 S.L.',
            address: '41.412995,2.161573',
            id: '43',
            demand: 32,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 36396,
                end: null,
            },
        },
        {
            name: 'FERRETERIA SEGURVI',
            address: '41.420258,2.149251',
            id: '44',
            demand: 18,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26352,
                end: null,
            },
        },
        {
            name: 'KAPIAL',
            address: '41.436221,2.189847',
            id: '45',
            demand: 20,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 27881,
                end: null,
            },
        },
        {
            name: 'RITUAL',
            address: '41.3868,2.159379',
            id: '46',
            demand: 9,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 36204,
                end: null,
            },
        },
        {
            name: 'BUGADERIA I TINTORERIA GRACIA',
            address: '41.400077,2.161675',
            id: '47',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26566,
                end: null,
            },
        },
        {
            name: 'ALFASONI',
            address: '41.408046,2.195875',
            id: '48',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 25629,
                end: null,
            },
        },
        {
            name: 'CONTROL 2000 DE JLD',
            address: '41.419227,2.209749',
            id: '49',
            demand: 36,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 28387,
                end: null,
            },
        },
        {
            name: 'ABUNDANT 2',
            address: '41.392986,2.15532',
            id: '50',
            demand: 26,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 25788,
                end: 32979,
            },
        },
        {
            name: 'LA BOTIGUETA DEL CABELL',
            address: '41.407632,2.14793',
            id: '51',
            demand: 35,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 27740,
                end: null,
            },
        },
        {
            name: 'MUEBLES DECORACIO',
            address: '41.405421,2.184622',
            id: '52',
            demand: 25,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26960,
                end: null,
            },
        },
        {
            name: 'PROESPORT',
            address: '41.442251,2.180871',
            id: '53',
            demand: 36,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 31299,
                end: null,
            },
        },
        {
            name: 'TINTORERIA HUNGRIA',
            address: '41.392734,2.155653',
            id: '54',
            demand: 27,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 25797,
                end: 32362,
            },
        },
        {
            name: 'FARMACIA',
            address: '41.401124,2.144243',
            id: '55',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 37273,
                end: null,
            },
        },
        {
            name: 'BYMAR FREIGHT FORWARDERS',
            address: '41.373765,2.174116',
            id: '56',
            demand: 23,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 38476,
                end: null,
            },
        },
        {
            name: 'ALUMINIS CRUCES',
            address: '41.383703,2.132239',
            id: '57',
            demand: 25,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 38803,
                end: null,
            },
        },
        {
            name: '//GUAL',
            address: '41.386201,2.155254',
            id: '58',
            demand: 4,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: null,
        },
        {
            name: 'PISOSMIL',
            address: '41.399709,2.151639',
            id: '59',
            demand: 35,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 25869,
                end: null,
            },
        },
        {
            name: 'BAR EL PETIT RACO',
            address: '41.385714,2.179728',
            id: '60',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 28087,
                end: null,
            },
        },
        {
            name: 'RESTAURANT EDELMANN',
            address: '41.384885,2.174034',
            id: '61',
            demand: 3,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28208,
                end: null,
            },
        },
        {
            name: 'NOU RACO 169',
            address: '41.391785,2.150128',
            id: '62',
            demand: 31,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 28366,
                end: null,
            },
        },
        {
            name: 'MONTISOL',
            address: '41.431723,2.177649',
            id: '63',
            demand: 38,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 27618,
                end: null,
            },
        },
        {
            name: 'SET UP',
            address: '41.396534,2.124582',
            id: '64',
            demand: 48,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 39543,
                end: 46146,
            },
        },
        {
            name: 'MAGATZEM PRIVAT',
            address: '41.386923,2.153135',
            id: '65',
            demand: 36,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 26441,
                end: null,
            },
        },
        {
            name: 'BAR RESTAURANT DONDE DARIO',
            address: '41.411823,2.17943',
            id: '66',
            demand: 48,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 25530,
                end: null,
            },
        },
        {
            name: 'ESPRESSAMENTE ILLY HÄAGEN DAZ',
            address: '41.389949,2.136485',
            id: '67',
            demand: 42,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 37843,
                end: null,
            },
        },
        {
            name: 'GM PEOPLE',
            address: '41.398577,2.182413',
            id: '68',
            demand: 50,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 25942,
                end: null,
            },
        },
        {
            name: 'RISTORANTE EDEN',
            address: '41.397218,2.16498',
            id: '69',
            demand: 15,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26829,
                end: null,
            },
        },
        {
            name: 'HIMALI',
            address: '41.402306,2.16123',
            id: '70',
            demand: 33,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 37148,
                end: 43422,
            },
        },
        {
            name: 'HIGIENSEC',
            address: '41.440784,2.192193',
            id: '71',
            demand: 42,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27638,
                end: 34015,
            },
        },
        {
            name: 'XARCUTERIA BALASCH',
            address: '41.411548,2.171109',
            id: '72',
            demand: 43,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 27412,
                end: null,
            },
        },
        {
            name: 'PERE PUCHE PERRUQUERS',
            address: '41.386598,2.131975',
            id: '73',
            demand: 23,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 28339,
                end: null,
            },
        },
        {
            name: "PUNT D'INFORMACIO TURISITICA I DE SERVEIS",
            address: '41.378832,2.19081',
            id: '74',
            demand: 49,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27736,
                end: null,
            },
        },
        {
            name: 'NUANJU PELL',
            address: '41.407011,2.163581',
            id: '75',
            demand: 13,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28884,
                end: null,
            },
        },
        {
            name: 'LA LLAUNETA DEL GUINARDO',
            address: '41.41645,2.176135',
            id: '76',
            demand: 18,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 25367,
                end: 26114,
            },
        },
        {
            name: 'FESTIVAL DES PAINS',
            address: '41.376659,2.16076',
            id: '77',
            demand: 17,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 25656,
                end: null,
            },
        },
        {
            name: 'BAR EXPRES',
            address: '41.416436,2.201956',
            id: '78',
            demand: 39,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 28439,
                end: 34718,
            },
        },
        {
            name: 'FILAFIL',
            address: '41.430276,2.186323',
            id: '79',
            demand: 46,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 28736,
                end: null,
            },
        },
        {
            name: 'LIGHT WINDOWS',
            address: '41.401017,2.165784',
            id: '80',
            demand: 32,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 25706,
                end: null,
            },
        },
        {
            name: 'CATALUNYA CAIXA',
            address: '41.430249,2.189291',
            id: '81',
            demand: 2,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 27324,
                end: null,
            },
        },
        {
            name: 'CAÑAS',
            address: '41.430544,2.186283',
            id: '82',
            demand: 30,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 26483,
                end: 29458,
            },
        },
        {
            name: 'BCN EXTRANGERIA',
            address: '41.395441,2.144772',
            id: '83',
            demand: 49,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 26203,
                end: null,
            },
        },
        {
            name: 'BANKROBBER',
            address: '41.401972,2.162997',
            id: '84',
            demand: 33,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 28604,
                end: null,
            },
        },
        {
            name: 'TRES ENCINAS',
            address: '41.386908,2.157416',
            id: '85',
            demand: 27,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: null,
        },
        {
            name: 'SPICA BCN',
            address: '41.401003,2.146349',
            id: '86',
            demand: 48,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 27063,
                end: null,
            },
        },
        {
            name: 'PESCADERIA CONCHI',
            address: '41.447755,2.17463',
            id: '87',
            demand: 15,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 27771,
                end: null,
            },
        },
        {
            name: 'CALÇATS TARRACO',
            address: '41.399964,2.179547',
            id: '88',
            demand: 27,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 31626,
                end: null,
            },
        },
        {
            name: 'NUBEAME',
            address: '41.389337,2.141822',
            id: '89',
            demand: 46,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 28771,
                end: 29343,
            },
        },
        {
            name: 'TRETZE',
            address: '41.40619,2.134028',
            id: '90',
            demand: 32,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: {
                start: 28242,
                end: null,
            },
        },
        {
            name: 'REFORMAS JULVIC S.C.P.',
            address: '41.407031,2.15905',
            id: '91',
            demand: 31,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 27230,
                end: null,
            },
        },
        {
            name: 'FARMACIA CARLOTA TORRES',
            address: '41.39129,2.125344',
            id: '92',
            demand: 49,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 27296,
                end: null,
            },
        },
        {
            name: 'TACTUM',
            address: '41.401565,2.157755',
            id: '93',
            demand: 37,
            serviceTime: null,
            deliveryZoneId: '4',
            deliveryWindow: {
                start: 25671,
                end: null,
            },
        },
        {
            name: 'CESAR FRANKEL',
            address: '41.398767,2.144332',
            id: '94',
            demand: 10,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26711,
                end: 28270,
            },
        },
        {
            name: 'PASEO A LA INDIA',
            address: '41.384075,2.174512',
            id: '95',
            demand: 28,
            serviceTime: null,
            deliveryZoneId: '1',
            deliveryWindow: {
                start: 26418,
                end: 33428,
            },
        },
        {
            name: 'BANC DE SABADELL',
            address: '41.396294,2.157544',
            id: '96',
            demand: 9,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 26330,
                end: null,
            },
        },
        {
            name: 'EUROTEK SBM',
            address: '41.415646,2.186219',
            id: '97',
            demand: 39,
            serviceTime: null,
            deliveryZoneId: '6',
            deliveryWindow: {
                start: 38838,
                end: null,
            },
        },
        {
            name: 'ALIMENTACIO',
            address: '41.411923,2.199404',
            id: '98',
            demand: 14,
            serviceTime: null,
            deliveryZoneId: '5',
            deliveryWindow: {
                start: 38196,
                end: null,
            },
        },
        {
            name: 'FORN DEGUSTACIO',
            address: '41.380941,2.136911',
            id: '99',
            demand: 12,
            serviceTime: null,
            deliveryZoneId: '3',
            deliveryWindow: {
                start: 36228,
                end: null,
            },
        },
        {
            name: 'HANDSEL AND GRANEL',
            address: '41.402124,2.150511',
            id: '100',
            demand: 45,
            serviceTime: null,
            deliveryZoneId: '2',
            deliveryWindow: null,
        },
    ],
};
